
import { test, expect, type Page } from '@playwright/test';
async function login(page:Page,role:'candidate'|'recruiter'|'admin',name:string){
  await page.goto('/#login/'+role);
  await page.getByText('Explore with a sample account',{exact:false}).click();
  await page.locator('.quick-login-item').filter({hasText:name}).getByRole('button',{name:'Log in',exact:true}).click();
  await expect(page.locator('.side-user .name')).toHaveText(name);
}
async function logout(page:Page){await page.getByRole('button',{name:'Sign out / switch account'}).click();await expect(page.getByRole('heading',{name:/Show the work/})).toBeVisible();}
test('mutual matching, two-way chat, reload persistence and safe text rendering',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await login(page,'candidate','Aisha Rahman');
  await page.locator('.dossier-card.top').getByRole('button',{name:'♥ Interested',exact:true}).click();
  await page.getByRole('button',{name:'Matches & Chat',exact:true}).click();
  await expect(page.getByText('No matches yet.',{exact:false})).toBeVisible();
  await logout(page);await login(page,'recruiter','Kabir Singh');
  await page.locator('.dossier-card.top').getByRole('button',{name:'♥ Interested',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:/Backend Engineer/}).click();
  await page.getByRole('button',{name:'Matches & Chat',exact:true}).click();
  await page.locator('.match-row').filter({hasText:'Aisha Rahman'}).click();
  await page.getByRole('textbox',{name:'Message',exact:true}).fill('Hello Aisha, let’s talk about this role.');
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await expect(page.locator('.bubble')).toContainText('Hello Aisha');
  await logout(page);await login(page,'candidate','Aisha Rahman');
  await page.getByRole('button',{name:'Matches & Chat',exact:true}).click();
  await page.locator('.match-row').filter({hasText:'Meridian Labs'}).click();
  await expect(page.locator('.bubble.them')).toContainText('Hello Aisha');
  await page.getByRole('textbox',{name:'Message',exact:true}).fill('<img src=x onerror=alert(1)> Thank you!');
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await expect(page.locator('.bubble.me')).toContainText('<img src=x onerror=alert(1)>');
  await expect(page.locator('.chat-body img')).toHaveCount(0);
  await page.reload();await page.locator('.match-row').filter({hasText:'Meridian Labs'}).click();
  await expect(page.locator('.bubble')).toHaveCount(2);
  expect(errors).toEqual([]);
});
test('challenge submission, admin review and badges survive account changes',async({page})=>{
  await page.goto('/');await login(page,'candidate','Aisha Rahman');
  await page.getByRole('button',{name:'Open Challenges',exact:true}).click();
  const challenge=page.locator('section.panel').filter({has:page.getByRole('heading',{name:'Build a rate limiter',exact:true})});
  await challenge.getByRole('textbox',{name:'Your submission'}).fill('I built a token bucket with atomic updates and bounded bursts.');
  await challenge.getByRole('button',{name:'Submit challenge'}).click();
  await expect(challenge.getByText('✓ Submitted')).toBeVisible();
  await logout(page);await login(page,'admin','Admin User');
  await page.locator('.list-row').filter({hasText:'I built a token bucket'}).getByRole('button',{name:'Mark reviewed'}).click();
  await page.getByRole('button',{name:'Award badges',exact:true}).click();
  await page.getByLabel('Candidate',{exact:true}).selectOption('cand1');
  await page.getByLabel('Badge',{exact:true}).selectOption('b2');
  await page.getByRole('button',{name:'Award badge',exact:true}).click();
  await expect(page.getByRole('status').filter({hasText:'Badge awarded'})).toBeVisible();
  await logout(page);await login(page,'candidate','Aisha Rahman');
  await page.getByRole('button',{name:'Profile',exact:true}).click();
  await expect(page.locator('.badge-chip').filter({hasText:'Design Sprint Winner'})).toBeVisible();
  await expect(page.getByText('I built a token bucket with atomic updates and bounded bursts.')).toBeVisible();
  await page.getByLabel('Name',{exact:true}).fill("Aisha O'Connor");
  await page.getByLabel('Skills (comma separated)').fill('PostgreSQL, API Design');
  await page.getByLabel('Portfolio paragraph',{exact:true}).fill('A detailed portfolio saved in the database.');
  await page.getByRole('button',{name:'Save profile'}).click();await page.reload();
  await expect(page.getByLabel('Name',{exact:true})).toHaveValue("Aisha O'Connor");
  await expect(page.getByLabel('Portfolio paragraph',{exact:true})).toHaveValue('A detailed portfolio saved in the database.');
});
test('recruiter job lifecycle, company search and challenge archive/restore/delete',async({page})=>{
  await page.goto('/');await login(page,'recruiter','Kabir Singh');
  await page.getByRole('button',{name:'+ Post a job',exact:true}).first().click();
  await page.getByLabel('Job title',{exact:true}).fill('Senior Database Engineer');
  await page.getByLabel('Location',{exact:true}).fill('Remote');
  await page.getByLabel('Pay range',{exact:true}).fill('₹20–30L/yr');
  await page.getByLabel('Short blurb (shown on swipe card)').fill('Build reliable data systems.');
  await page.getByLabel('Full description').fill('Use PostgreSQL to build a better ledger.');
  await page.getByRole('button',{name:'Post job',exact:true}).click();
  let row=page.locator('.list-row').filter({has:page.getByRole('heading',{name:'Senior Database Engineer',exact:true})});
  await row.getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByRole('dialog').getByLabel('Job title',{exact:true}).fill('Staff Database Engineer');
  await page.getByRole('button',{name:'Save job',exact:true}).click();
  row=page.locator('.list-row').filter({has:page.getByRole('heading',{name:'Staff Database Engineer',exact:true})});
  await row.getByRole('button',{name:'Close',exact:true}).click();
  await expect(row.getByRole('button',{name:'Reopen'})).toBeVisible();
  await row.getByRole('button',{name:'Reopen'}).click();
  await logout(page);await login(page,'candidate','Rohan Verma');
  await page.getByRole('button',{name:'Search jobs',exact:true}).click();
  const search=page.getByRole('textbox',{name:'Search by job title, company, or sector…'});
  await search.pressSequentially('Staff Database Engineer');
  await expect(search).toBeFocused();
  await page.getByRole('button',{name:/Staff Database Engineer/}).click();
  await expect(page.getByRole('dialog').getByText('Use PostgreSQL to build a better ledger.')).toBeVisible();
  await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
  await logout(page);await login(page,'admin','Admin User');
  await page.getByRole('button',{name:'Challenges',exact:true}).click();
  await page.getByLabel('Challenge title',{exact:true}).fill('Temporary challenge');
  await page.getByLabel('Description',{exact:true}).fill('Write a thoughtful response.');
  await page.getByRole('button',{name:'Post challenge',exact:true}).click();
  const challenge=page.locator('section.submission-box').filter({has:page.getByRole('heading',{name:'Temporary challenge',exact:true})});
  await challenge.getByRole('button',{name:'Archive',exact:true}).click();
  await page.getByRole('button',{name:'Archived',exact:true}).click();
  await challenge.getByRole('button',{name:'Restore',exact:true}).click();
  await page.getByRole('button',{name:'Active',exact:true}).click();
  await challenge.getByRole('button',{name:'Delete',exact:true}).click();
  await page.getByRole('dialog').getByRole('button',{name:'Delete challenge',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Temporary challenge',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Backend data',exact:true}).click();
  await expect(page.locator('table.data-table')).toHaveCount(6);
});
test('desktop and mobile design, touch swipe and no horizontal overflow',async({page})=>{
  await page.setViewportSize({width:1440,height:1000});await page.goto('/');
  await page.screenshot({path:'test-results/landing-desktop.png',fullPage:true});
  await login(page,'candidate','Aisha Rahman');
  await page.screenshot({path:'test-results/candidate-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('button',{name:'Home',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/candidate-mobile.png',fullPage:true});
  const card=page.locator('.dossier-card.top'),first=await card.locator('h3').innerText();
  const bounds=await card.boundingBox();expect(bounds).toBeTruthy();
  await page.mouse.move(bounds!.x+100,bounds!.y+200);await page.mouse.down();await page.mouse.move(bounds!.x-60,bounds!.y+200,{steps:10});await page.mouse.up();
  await expect(page.locator('.dossier-card.top h3')).not.toHaveText(first);
});
